all:
  hosts:
    laidun:
    lab:
    deploy:
    pihole:
    camera:
    ubu:
  children:
    local:
      hosts:
        lab:
        deploy:
        pihole:
        camera:
        ubu:
    dns:
      hosts:
        lab:
    docker:
      hosts:
        lab:
        pihole:
        ubu:
    monitor_server:
      hosts:
        ubu:
    vpn:
      hosts:
        camera:
        ubu:
    dyfi:
      hosts:
        pihole:
    raspi:
      hosts:
        deploy:
        pihole:
        ubu:
        lab:
    certbot:
      hosts:
        camera:
  vars:
    ansible_user: "{{ username }}"
    ansible_ssh_pass: "{{ password }}"
    ansible_become_pass: "{{ password }}"
