all:
  hosts:
    laidun:
  children:
    local:
      hosts:
        lab:
        deploy:
        pihole:
    dns:
      hosts:
        lab:
    docker:
      hosts:
        lab:
  vars:
    ansible_user: "{{ username }}"
    ansible_ssh_pass: "{{ password }}"
    ansible_become_pass: "{{ password }}"
