all:
  hosts:
    laidun:
    # pilvilaidun:
  children:
    local:
      hosts:
        lab:
        deploy:
        pihole:
        camera:
        motioneyeos:
    dns:
      hosts:
        lab:
    docker:
      hosts:
        lab:
        pihole:
    monitor_server:
      hosts:
        lab:
        pihole:
    vpn:
      hosts:
        lab:
        camera:
        laidun:
    dyfi:
      hosts:
        pihole:
    raspi:
      hosts:
        deploy:
        pihole:
  vars:
    ansible_user: "{{ username }}"
    ansible_ssh_pass: "{{ password }}"
    ansible_become_pass: "{{ password }}"
