---
- name: Remove user 'pi'
  remote_user: "{{ username }}"
  hosts: raspi
  become: yes
  vars_files:
    - vault.yml
  tasks:
    - name: Remove user 'pi'
      user:
        name: pi
        state: absent
        remove: yes

