---
- name: Create another user {{ new_user }} 
  remote_user: pi
  hosts: raspi
  become: yes
  gather_facts: false
  vars_files:
    - pi_vault.yml
  tasks:
    - name: Create user {{ new_user }}
      user:
        name: "{{ new_user }}"
        groups: sudo
        append: yes
        password: "{{ new_user_password | password_hash('sha512')  }}"
        update_password: on_create

