# Here are the dependencies for running all the playbooks

# Prometheus server
- src: https://github.com/cloudalchemy/ansible-prometheus.git

# Alertmanager for prometheus
- src: https://github.com/cloudalchemy/ansible-alertmanager.git

# Node exporter for monitoring hosts
- src: https://github.com/cloudalchemy/ansible-node-exporter.git

# Blackbox exporter for monitoring remote hosts
- src: https://github.com/cloudalchemy/ansible-blackbox-exporter.git

# SNMP exporter for monitoring network devices
- src: https://github.com/cloudalchemy/ansible-snmp-exporter.git 

# Ansible role for Unbound DNS server
- src: https://github.com/jdauphant/ansible-role-unbound.git

# Wireguard
- src: https://github.com/githubixx/ansible-role-wireguard.git

# NTP
- src: https://github.com/geerlingguy/ansible-role-ntp.git

# cAdvisor
# - src: https://github.com/ome/ansible-role-cadvisor.git

# Dy.fi
- src: https://github.com/tmrtkn/ansible-role-dyfi.git

# ansible-raspi-config
- src: https://github.com/mikolak-net/ansible-raspi-config.git
