---
- name: Remove user 'ubuntu'
  remote_user: "{{ username }}"
  hosts: ubuntu
  gather_facts: false
  become: yes
  vars_files:
    - vault.yml
  tasks:
    - name: Remove user 'ubuntu'
      user:
        name: ubuntu
        state: absent
        remove: yes

