---
# tasks file for ansible-role-netatmo-exporter-docker




# Check if the netatmo-exporter directory already exists
 - name: Check if the netatmo-exporter directory already exists
   stat:
    path: "{{ netatmo_exporter_dir }}"
   register: netatmo_dir

# Download code from github
 - name: Download netatmo-exporter from GitHub
   become: no
   git:
     repo: "https://github.com/xperimental/netatmo-exporter.git"
     dest: "{{ netatmo_exporter_dir }}"
   when: not netatmo_dir.stat.exists

# TODO:
 # - name: Edit Dockerfile and change image base from busybox to arm32v7/alpine so that the timezone can be set
 #         if this is rpi
 #   become: no
 #   lineinfile:
 #     path: "{{ netatmo_exporter_dir }}/Dockerfile"
 #     regexp: "^GO_ARCH="
 #     insertbefore: ".+\\?\\=+"
 #     firstmatch: yes
 #     line: "GO_ARCH=arm"
 #   when: ansible_architecture == "armv7l" and not netatmo_dir.stat.exists

# TODO: If this is rpi and previous step is done, then we need to also add the tzdata package to Dockerfile

# Edit the Makefile and say that we are on raspberry pi, if we are
 - name: Edit makefile if this is rpi (32bit)
   become: no
   lineinfile:
     path: "{{ netatmo_exporter_dir }}/Makefile"
     regexp: "^GO_ARCH="
     insertbefore: ".+\\?\\=+"
     firstmatch: yes
     line: "GO_ARCH=arm"
   when: ansible_architecture == "armv7l" and not netatmo_dir.stat.exists

# Edit the Makefile and say that we are on raspberry pi, if we are
 - name: Edit makefile if this is rpi (64 bit)
   become: no
   lineinfile:
     path: "{{ netatmo_exporter_dir }}/Makefile"
     regexp: "^GO_ARCH="
     insertbefore: ".+\\?\\=+"
     firstmatch: yes
     line: "GO_ARCH=arm64"
   when: ansible_architecture == "aarch64" and not netatmo_dir.stat.exists

# Build an image
 - name: Build netatmo-exporter Docker image
   become: no
   docker_image:
     name: "{{ docker_netatmo_exporter_image }}"
     build: 
       path: "{{ netatmo_exporter_dir }}"
     source: build

 - name: Create timezone file
   become: no
   copy:
     dest: "{{ netatmo_exporter_dir }}/TZ"
     content: |
       {{ docker_netatmo_exporter_timezone }}
   when: docker_netatmo_exporter_timezone is defined

# Start an image
 - name: Start netatmo-exporter docker container
   docker_container:
     name: "{{ docker_netatmo_exporter_container_name }}"
     image: "{{ docker_netatmo_exporter_image }}"
     state: started
     restart: yes
     restart_policy: unless-stopped
     networks_cli_compatible: yes
     network_mode: "{{ docker_netatmo_exporter_network_mode }}"
     # volumes:
     #   # - "/etc/localtime:/etc/localtime:ro"
       # - "{{ netatmo_exporter_dir }}/TZ:/etc/TZ:ro"
     env:
       TZ: "{{ docker_netatmo_exporter_timezone }}"
       NETATMO_EXPORTER_ADDR: "0.0.0.0:9210"
       NETATMO_CLIENT_ID: "{{ netatmo_client_id }}"
       NETATMO_CLIENT_SECRET: "{{ netatmo_client_secret }}" 
       NETATMO_CLIENT_USERNAME: "{{ netatmo_client_username }}"
       NETATMO_CLIENT_PASSWORD: "{{ netatmo_client_password }}"
       # UCLIBC_TZ_FILE_PATH: "/etc/localtime"

# TODO: Check that this is running ok.
