---
# defaults file for server


system_timezone: "Europe/Helsinki"
system_locale: "en_US.UTF-8"

# Install these packages
system_packages: []

system_tmpfs_mounts:
  - { src: "/run", size: "10%", options: "nodev,noexec,nosuid"  }
  - { src: "/tmp", size: "10%", options: "nodev,nosuid"  }
  - { src: "/var/log", size: "10%", options: "nodev,noexec,nosuid"  }

system_default_editor_path: "/usr/bin/vi"

logwatch_tmp_dir: /var/cache/logwatch
logwatch_mailto: "root"
logwatch_detail: "Low"
logwatch_interval: "daily"

postfix_hostname: "{{ ansible_hostname }}"
postfix_mailname: "{{ ansible_hostname }}"
postfix_mydestination:
  - "{{ postfix_hostname }}"
  - localdomain
  - localhost
  - localhost.localdomain
postfix_relayhost: smtp.gmail.com
postfix_relayhost_port: 587
postfix_sasl_user: "{{ postfix_sasl_user }}"
postfix_sasl_user_password: "{{ postfix_sasl_user_password }}"
postfix_smtp_tls_cafile: /etc/ssl/certs/ca-certificates.crt

ssh_sshd_config: "/etc/ssh/sshd_config"
ssh_banner:

