---
language: python
python: "2.7"
dist: xenial
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-apt python-pycurl
install:
  - pip install ansible
script:
  - echo localhost > inventory
  - ansible-playbook -i inventory --syntax-check --list-tasks role.yml
  - ansible-playbook -i inventory --connection=local --become --become-method sudo -vvvv role.yml
notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
