---

 - name: Make mountpoints
   file:
     path: "{{ item.path }}"
     state: directory
   with_items: "{{ mountpoints }}"
   when: mountpoints is defined

 - name: Mount filesystems
   mount:
     path: "{{ item.path }}"
     src: UUID={{ item.uuid }}
     fstype: "{{ item.fstype }}"
     state: present
     opts: "defaults,{{ item.opts }}"
   with_items: "{{ mountpoints }}"
   when: mountpoints is defined

