---

 - name: mount other filesystems
   mount:
     path: "{{ item.path }}"
     src: UUID={{ item.uuid }}
     fstype: "{{ item.fstype }}"
     state: present
     opts: "defaults,{{ item.opts }}"
   with_items: "{{ mountpoints }}"
   when: mountpoints is defined

