---
# tasks file for pihole

 - name: Check if docker is installed
   command: docker
   register: docker_installed
   ignore_errors: true
   
 - name: Install packages needed for docker install
   apt: 
     name: curl
     state: present
   when: docker_installed.rc != 0

 - name: Get and run convenience script for raspbian
   shell: curl -sSL https://get.docker.com/ | sh
   when: docker_installed.rc != 0

 - name: Execute docker install
   command: /tmp/get-docker.sh
   become: yes
   when: docker_installed.rc != 0

 - name: Install python-docker
   apt:
     name: python3-docker
     state: present

 - name: Add user to docker group
   user:
     name: "{{ username }}"
     append: yes
     groups: docker
  

   
